import tiktoken
import sys

# --- 价格定义 ---
# 这些价格是根据您的 cot_runner.py 脚本中的
# `summarize_run` 函数硬编码的 (2*... + 8*...)
# 这也与您 api_pricing.py 中 "gpt-4.1" 的价格一致
PRICE_PROMPT_PER_MILLION = 2.0
PRICE_COMPLETION_PER_MILLION = 8.0

def count_tokens_with_tiktoken(text: str) -> int:
    """
    使用 tiktoken (cl100k_base) 计算 token 数量，
    这与 cot_runner.py 中用于 GPT 模型的逻辑一致。
    """
    try:
        # 'cl100k_base' 是用于 GPT-4, GPT-3.5-Turbo, GPT-4o 和 GPT-4.1 的标准编码
        encoding = tiktoken.get_encoding("cl100k_base")
    except Exception as e:
        print(f"错误: 无法加载 tiktoken 编码 'cl100k_base'。")
        print(f"请确保您已经安装了 tiktoken: pip install tiktoken")
        print(f"详细错误: {e}")
        sys.exit(1)
        
    return len(encoding.encode(text))

def calculate_cost_from_cot_runner(prompt: str, completion: str):
    """
    根据 cot_runner.py 的逻辑计算成本。
    """
    print("--- 正在使用 'cot_runner.py' (tiktoken) 逻辑进行计算 ---")

    # 1. 价格
    print(f"价格 (每 1M tokens):")
    print(f"  - Prompt:     ${PRICE_PROMPT_PER_MILLION:.4f}")
    print(f"  - Completion: ${PRICE_COMPLETION_PER_MILLION:.4f}")

    # 2. 计算 Token 数量 (使用 tiktoken)
    prompt_tokens = count_tokens_with_tiktoken(prompt)
    completion_tokens = count_tokens_with_tiktoken(completion)

    print("\nToken 数量 (使用 tiktoken 'cl100k_base' 估算):")
    print(f"  - Prompt:     {prompt_tokens} tokens")
    print(f"  - Completion: {completion_tokens} tokens")

    # 3. 计算总成本
    prompt_cost = (prompt_tokens / 1_000_000) * PRICE_PROMPT_PER_MILLION
    completion_cost = (completion_tokens / 1_000_000) * PRICE_COMPLETION_PER_MILLION
    total_cost = prompt_cost + completion_cost

    print("\n计算成本:")
    print(f"  - Prompt 成本:     ${prompt_cost:.8f}")
    print(f"  - Completion 成本: ${completion_cost:.8f}")
    print(f"  - 总成本:          ${total_cost:.8f}")
    print("--------------------------------------------------")
    
    return total_cost

# --- 脚本主程序 ---
if __name__ == "__main__":
    
    # --- 在这里定义您的预设输入和输出 ---
    
    test_prompt = "this is a sample text for cost calculation."
    
    test_completion = "this is a sample response generated by the model. We will use this text to calculate the cost for the completion.<<<<++++======|||||,,,,,,,33312"
    
    print(f"测试 Prompt:\n\"{test_prompt}\"\n")
    print(f"测试 Completion:\n\"{test_completion}\"\n")
    
    # 运行计算
    calculate_cost_from_cot_runner(test_prompt, test_completion)