import sys
import os

# --- 导入您提供的脚本中的功能 ---
try:
    # 1. 从 api_pricing.py 导入价格函数
    from api_pricing import get_model_pricing
except ImportError:
    print("错误: 无法导入 'api_pricing'.")
    print("请确保 'api_pricing.py' 与此脚本在同一目录中。")
    sys.exit(1)

try:
    # 2. 从 token_patch.py 导入 token 计算函数
    from token_patch import count_deepseek_tokens
except ImportError:
    print("错误: 无法导入 'count_deepseek_tokens'.")
    print("请确保 'token_patch.py' 与此脚本在同一目录中。")
    sys.exit(1)
except Exception as e:
    print(f"错误: 尝试从 'token_patch.py' 导入时出错。")
    print("这通常意味着 'deepseek_v3_tokenizer' 文件夹丢失或 'transformers' 未安装。")
    print(f"详细信息: {e}")
    sys.exit(1)

# --- 模拟 'log_config' 模块 ---
# 您的 'api_pricing.py' 脚本导入了 'log_config'。
# 为了使这个测试脚本独立运行（以防您没有 log_config.py），
# 我们将创建一个虚拟的模拟版本来防止导入错误。
if "log_config" not in sys.modules:
    
    class MockLogger:
        """一个虚拟的日志记录器，不做任何事，但可以被调用。"""
        def warning(self, msg):
            print(f"LOG_WARNING: {msg}")
        def error(self, msg, exc_info=False):
            print(f"LOG_ERROR: {msg}")
        def info(self, msg):
            print(f"LOG_INFO: {msg}")

    class MockLogConfig:
        """一个虚拟的配置模块，用于返回虚拟日志记录器。"""
        def get_logger(self):
            return MockLogger()
        
        def setup_logger(self, *args, **kwargs):
            pass  # 什么也不做
        
        def log_separator(self):
            pass  # 什么也不做

    # 将我们的虚拟模块注入 Python 的模块列表
    sys.modules['log_config'] = MockLogConfig()


def calculate_cost_from_text(prompt, completion, model_name):
    """
    根据预设的输入、输出和模型名称计算 API 成本。
    """
    print(f"--- 正在计算模型: {model_name} ---")
    
    # 1. 获取模型定价
    # 这是从您的 api_pricing.py 调用的
    pricing = get_model_pricing(model_name)
    
    if pricing['prompt'] == 0.0 and pricing['completion'] == 0.0:
        print(f"警告: 在 'api_pricing.py' 中未找到模型 '{model_name}' 或其价格为 $0.0。")
        # 脚本将继续，但成本将为 0
    
    print(f"价格 (每 1M tokens):")
    print(f"  - Prompt:     ${pricing['prompt']:.4f}")
    print(f"  - Completion: ${pricing['completion']:.4f}")
    
    # 2. 计算 Token 数量
    # 这是从您的 token_patch.py 调用的
    # 注意：这将使用 DeepSeek tokenizer 来估算 token
    try:
        prompt_tokens = count_deepseek_tokens(prompt)
        completion_tokens = count_deepseek_tokens(completion)
    except Exception as e:
        print(f"\n错误: 计算 token 失败。")
        print(f"请确保 'deepseek_v3_tokenizer' 文件夹存在于此目录中。")
        print(f"详细信息: {e}")
        return

    print("\nToken 数量 (使用 DeepSeek tokenizer 估算):")
    print(f"  - Prompt:     {prompt_tokens} tokens")
    print(f"  - Completion: {completion_tokens} tokens")

    # 3. 计算总成本
    # 价格是按百万 (1,000,000) token 计算的
    prompt_cost = (prompt_tokens / 1_000_000) * pricing['prompt']
    completion_cost = (completion_tokens / 1_000_000) * pricing['completion']
    total_cost = prompt_cost + completion_cost

    print("\n计算成本:")
    print(f"  - Prompt 成本:     ${prompt_cost:.8f}")
    print(f"  - Completion 成本: ${completion_cost:.8f}")
    print(f"  - 总成本:          ${total_cost:.8f}")
    print("--------------------------------------------------")
    
    return total_cost

# --- 脚本主程序 ---
if __name__ == "__main__":
    
    # --- 在这里定义您的预设输入和输出 ---
    
    test_prompt = "this is a sample text for cost calculation."
    
    test_completion = "this is a sample response generated by the model. We will use this text to calculate the cost for the completion.<<<<++++======|||||,,,,,,,33312"
    '''
    - Prompt 成本:     $0.00001400
    - Completion 成本: $0.00015200
    - 总成本:          $0.00016600
    '''
    # --- 您要求的模型 ---
    
    model_to_test = "gpt-4.1"
    
    print(f"测试 Prompt:\n\"{test_prompt}\"\n")
    print(f"测试 Completion:\n\"{test_completion}\"\n")
    
    # 运行计算
    calculate_cost_from_text(test_prompt, test_completion, model_to_test)